// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmDssdJjNHJgw10DIfCvX1hmjomcJ9KmM',
    appId: '1:838968030281:android:133672c8f6ecf3a88c7b98',
    messagingSenderId: '838968030281',
    projectId: 'nsuns-26e64',
    storageBucket: 'nsuns-26e64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeTseV5niSCmW3b3vi4fKf71_Y8fVu3yA',
    appId: '1:838968030281:ios:92d5eb8151c7615c8c7b98',
    messagingSenderId: '838968030281',
    projectId: 'nsuns-26e64',
    storageBucket: 'nsuns-26e64.appspot.com',
    iosClientId: '838968030281-rh4q9rmgur3mb15jg93i2cshc2aa78en.apps.googleusercontent.com',
    iosBundleId: 'dev.jasonmatthew.nsuns',
  );
}
